name: SFTP Deploy

on:
  push:
    branches:
      - main  # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22  # usually 22 for SFTP
          source: "./"  # upload all repo files
          target: "/home/zopa/public_html/zopa"  # your remote directory, change accordingly
          rm: true  # optional: remove remote files before upload to avoid stale files
