name: SFTP Deploy

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to SFTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_HOST }}          # IP or domain of your server
          username: ${{ secrets.SFTP_USERNAME }}    # Your server's username
          password: ${{ secrets.SFTP_PASSWORD }}    # Your server's password
          protocol: sftp                            # Use sftp for secure upload
          port: 22                                  # Default SFTP port
          local-dir: ./                             # Upload everything in the repo
          server-dir: /home/zopa/public_html/zopa   # Remote directory path
