name: Deploy via Rsync

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy files with rsync
        uses: burnett01/rsync-deployments@v4.2
        with:
          switches: -avz --delete          # Archive, verbose, compress, delete remote files not present locally
          path: ./                         # Local directory to sync (root of repo)
          remote_path: /home/zopa/public_html/zopa   # Remote target directory
          remote_host: ${{ secrets.SFTP_HOST }}      # Your server host
          remote_user: ${{ secrets.SFTP_USERNAME }}  # SSH user on server
          remote_key: ${{ secrets.SFTP_PASSWORD }} # SSH private key (add to your repo secrets)
