name: SFTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          source: "."  # use "." instead of "./" for better compatibility
          target: "/home/zopa/public_html/zopa"
          rm: false  # safer; set to true only if you're sure
          timeout: 60s  # default is 30s; increase if needed
          command_timeout: 60s  # avoid timeout on large files
          strip_components: 0  # prevent flattening
          debug: true  # enables verbose output for troubleshooting
