name: Deploy via Rsync

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy files with rsync
        uses: burnett01/rsync-deployments@v7.0.2
        with:
          switches: -avz --delete
          path: ./
          remote_path: /home/zopa/public_html/zopa
          remote_host: ${{ secrets.SFTP_HOST }}
          remote_user: ${{ secrets.SFTP_USERNAME }}
          remote_key: ${{ secrets.SFTP_PASSWORD }} # SSH private key (add to your repo secrets)
